baseurl       = "localhost"
title         = "My Blog"
languageCode  = "en-us"
theme         = "hello-friend-ng"
paginate      = 10
enableGitInfo = true

[params]
  dateform              = "Jan 2, 2006"
  dateformShort         = "Jan 2"
  dateformNum           = "2006-01-02"
  dateformNumTime       = "2006-01-02 15:04"
  homeSubtitle          = "Linux System Administrator | Open-Source Enthusiast"
  disableReadOtherPosts = false
  enableSharingButtons  = true
  description           = "My new homepage or blog"
  keywords              = "homepage, blog"
  images                = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title          = "Hi, I'm Anton"
    keywords       = ""
    copyright      = '<a href = "https://creativecommons.org/licenses/by-nc/4.0/" target = "_blank" rel = "noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText     = "$ cd /home/Anton/"
      logoHomeLink = "/"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "blog"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"

  [[params.social]]
    name = "github"
    url  = "https://www.github.com/AntonVanAssche"

  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/AntonVanAssche"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/anton-van-assche/"

  [[params.social]]
    name = "email"
    url  = "mailto:vanasscheanton@duck.com"

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
