baseurl            = "localhost"
title              = "My Blog"
languageCode       = "en-us"
theme              = "anatole"
paginate           = 10
enableGitInfo      = true
enableRobotsTXT    = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
title                = "Hi, I'm Anton"
author               = "Anton Van Assche"
profilePicture       = "profile.jpg"
description          = "Linux System Administrator | Open-Source Enthusiast"
copyright            = "2024-{{ YEAR }}"
singleDateFormat     = "Mon, Jan 2, 2006"
indexDateFormat      = "Mon, Jan 2, 2006"
listDateFormat       = "Jan 2"
doNotLoadAnimations  = true
customCss            = ["css/syntax.css"]
displayMode          = "light"
disableThemeSwitcher = true

  [[params.socialIcons]]
    icon = "fab fa-github"
    name = "github"
    url  = "https://www.github.com/AntonVanAssche"

  [[params.socialIcons]]
    icon = "fab fa-gitlab"
    name = "gitlab"
    url  = "https://gitlab.com/AntonVanAssche"

  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    name = "linkedin"
    url  = "https://www.linkedin.com/in/anton-van-assche/"

  [[params.socialIcons]]
    icon = "fas fa-envelope"
    name = "email"
    url  = "mailto:vanasscheanton@duck.com"

  [[params.socialIcons]]
    icon = "fa fa-key"
    name = "pgp"
    url  = "https://keyserver.ubuntu.com/pks/lookup?search=0x3ff8016d27683e3e&op=vindex"

[menu]
  [[menu.main]]
  name       = "Home"
  identifier = "home"
  weight     = 100
  url        = "/"

  [[menu.main]]
  name       = "About"
  weight     = 200
  identifier = "about"
  url        = "/about/"

  [[menu.main]]
  name       = "Posts"
  weight     = 300
  identifier = "posts"
  url        = "/post/"

  [[menu.main]]
  name       = "Projects"
  weight     = 400
  identifier = "projects"
  url        = "/projects/"

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
